version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backendpoops/:/usr/src/app/
    ports:
      - 8000:8000
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ivancheng
      - POSTGRES_USER=backendpoops
      - POSTGRES_PASSWORD=poops